name: web

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  grpc: ^3.0.2
  intl: ^0.17.0
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.2
  build_web_compilers: ^3.2.1
  lints: ^1.0.1
